### PR TITLE
cmake: Make OpenThread cache variables reconfigurable

### PR DESCRIPTION
**Pull request by rlubos**
All of the OpenThread configuration variables are cache variables, which
are persistent across runs and not being overwritten by default. This
casue an undesired behaviour, that only the initial configuration is
being applied for OpenThread, making it indifferent for any following
Kconfig changes.

Fix this, by adding `FORCE` parameter when setting the variable,
therefore ensuring that the variable value gets updated. Additionally,
set the variable to OFF explicity in case the respetive Kconfig option
is disabled. Both of these changes ensure that the configuration used by
OpenThread is in sync with the current Kconfig configuration.

Signed-off-by: Robert Lubos <robert.lubos@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
@tejlmand An alternative solution I've identified is to use "normal" variable instead of cache, and enforce [CMP0077](https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077) policy with `set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)`. This makes the `option()` used by OpenThread a noop, if a "normal" cmake variable already exists.

I've chosen this approach though, as it keeps the CMakeCache.txt contents up to date with the actual OpenThread configuratoin, so there should be less confusion. But I wanted to hear from you if this is a good way to go, or perhaps there is some other solution I have not found out.

**Comment by rlubos** [comment]
CC @edmont @MarekPorwisz

**Review by MarekPorwisz — APPROVED** [review]

**Review by edmont — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Comment by tejlmand** [comment]
> @tejlmand An alternative solution I've identified is to use "normal" variable instead of cache, and enforce [CMP0077](https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077) policy with `set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)`. This makes the `option()` used by OpenThread a noop, if a "normal" cmake variable already exists.

I think your current proposal is the best in this situation.

**Review by tejlmand — APPROVED** [review]

**Comment by rlubos** [comment]
@carlescufi Sorry for bothering again, but I still need a green "tick" on this PR in order to merge...

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
