### PR TITLE
Upmerge

### PR DESCRIPTION
**Pull request by rlubos**
Regular upmerge.

### CODE REVIEW

**Comment by rlubos** [comment]
Corresponding PR: https://github.com/zephyrproject-rtos/zephyr/pull/26243

**Comment by rlubos** [comment]
cc @MarekPorwisz @lmaciejonczyk

**Comment by carlescufi** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/26243 is green, merging

**Comment by carlescufi** [comment]
Actually @rlubos should I merge or will you push?

**Comment by rlubos** [comment]
@carlescufi I'll push, thanks!

**Pull request merged**
