### PR TITLE
logging: Removed outdated NCP_SPINEL log output.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
In OpenThread OPENTHREAD_CONFIG_LOG_OUTPUT_NCP_SPINEL
was removed and all occurences were replaced
with OPENTHREAD_CONFIG_LOG_OUTPUT_APP, so change is required
to keep compatibility.

Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>

### CODE REVIEW

**Comment by MaureenHelm** [comment]
Is there a corresponding PR to the main zephyr repo updating `west.yml`?

**Comment by kkasperczyk-no** [comment]
> Is there a corresponding PR to the main zephyr repo updating `west.yml`?

Actually this change is invoked by this one (https://github.com/zephyrproject-rtos/openthread/commit/b66ac5d9071d1ae6334cdc2947422c7980dee793) in OpenThread, which was merged to Zephyr master long ago, but I didn't notice it and OPENTHREAD_CONFIG_LOG_OUTPUT_NCP_SPINEL was still used in zephyr/CMakeLists.txt file.

**Comment by carlescufi** [comment]
@kkasperczyk-no you still need to update the SHA in zephyr's west.yml in order for this PR to be merged, so please open a PR there pointing to this PR

**Comment by kkasperczyk-no** [comment]
> @kkasperczyk-no you still need to update the SHA in zephyr's west.yml in order for this PR to be merged, so please open a PR there pointing to this PR

@carlescufi Right, it's done

**Pull request merged**
